"""The learning-failure table of the appendix: which learning layouts (seeds 100-299) each arm ended
wrong. A row per seed that any arm failed, hardest (most failing runs) first; a column per arm, worst
arm (most failures per run) on the left; one mark per failing run (T timeout, W watchdog, C collision,
H a wrong human call or a missing one), so the scripted rules' single run shows at most one mark and
the three-run arms up to three.

    python scripts/analysis/learning_failures.py    # -> results/tables/learning_failures.md
"""
from __future__ import annotations

import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
DATA = os.environ.get("RUNS", os.path.join(REPO, "results", "runs"))
OUT = os.path.join(REPO, "results", "tables", "learning_failures.md")

ARMS = [  # label, run names
    ("Scripted rules", ["scripted_learning"]),
    ("Distillation alone", ["distillation_r1", "distillation_r2", "distillation_r3"]),
    ("Without replay", ["experience_noreplay_r1", "experience_noreplay_r2", "experience_noreplay_r3"]),
    ("Method", ["method_r1", "method_r2", "method_r3"]),
]
MARK = {"timeout": "T", "watchdog": "W", "collision": "C"}


def failures(run: str) -> dict[int, str]:
    """seed -> termination letter for every episode of the run that ended wrong."""
    out = {}
    for f in sorted(glob.glob(os.path.join(DATA, run, "episode_*.json"))):
        s = json.load(open(f))["summary"]
        right = bool(s["success"]) if s.get("success") is not None else s["termination"] == "goal"
        if not right:
            out[s["seed"]] = MARK.get(s["termination"], "H")
    return out


def main() -> None:
    per_arm = [(label, [failures(r) for r in runs]) for label, runs in ARMS]
    # worst arm (most failures per run, since the rules ran once) on the left; ties by seeds failed
    per_arm.sort(key=lambda a: (-sum(len(f) for f in a[1]) / len(a[1]), -len({s for f in a[1] for s in f})))
    seeds = sorted({s for _, fs in per_arm for f in fs for s in f})
    marks = {s: ["".join(f.get(s, "") for f in fs) for _, fs in per_arm] for s in seeds}
    seeds.sort(key=lambda s: (-sum(len(m) for m in marks[s]), -sum(1 for m in marks[s] if m), s))
    head = ["Seed"] + [label for label, _ in per_arm] + ["Failing runs"]
    lines = ["| " + " | ".join(head) + " |", "|" + "|".join(["---:"] + [":---:"] * (len(head) - 1)) + "|"]
    for s in seeds:
        lines.append("| " + " | ".join([str(s)] + marks[s] + [str(sum(len(m) for m in marks[s]))]) + " |")
    tot = ["Failures / runs"] + [f"{sum(len(f) for f in fs)} / {len(fs)}" for _, fs in per_arm] + [""]
    lines.append("| " + " | ".join(f"**{t}**" if t else "" for t in tot) + " |")
    text = ("# Learning layouts ended wrong\n\nGenerated by `scripts/analysis/learning_failures.py`. One letter per "
            "failing run (T timeout, W watchdog, C collision, H human call wrong or missing); the scripted rules ran "
            "once, the other arms three times. Rows: hardest first. Columns: worst arm (most failures per run) left.\n\n"
            + "\n".join(lines) + "\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(text)
    print("wrote", OUT)


if __name__ == "__main__":
    main()
